In [14]:
import numpy as np

In [15]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [16]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [17]:
type(arr1)

numpy.ndarray

In [18]:
# nf = n-Dimensional
list2 = [21, 32, 11]

In [19]:
arr2 = np.arange(10, 20, 1) #start, stop (non inclusive), step-size
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
list3 = [list1, list2]
list3

[[10, 20, 30], [21, 32, 11]]

In [23]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [21, 32, 11]])

In [25]:
arr3.shape

(2, 3)

In [26]:
arr3dim = np.array(
    [
        [
            [1, 2, 3], [3, 4, 5]
        ],
        [
            [5,6,7], [7, 8, 9]
        ] 
    ]
)
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [27]:
arr3dim.shape

(2, 2, 3)

In [28]:
list1

[10, 20, 30]

In [29]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [31]:
arr1

array([10, 20, 30])

In [34]:
arr11 = np.array(list2)

In [35]:
arr11

array([21, 32, 11])

In [37]:
arr1.shape == arr11.shape

True

In [38]:
arr1 * arr11

array([210, 640, 330])

In [42]:
arr1

array([10, 20, 30])

In [44]:
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [46]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

In [48]:
## LAb
# create ndarrays of the following size:
#     1. One dimensional array with 12 elements (12, )
#     2. Two dimensional array of size (3, 4)
#     3. Three dimensional array of size (2, 5, 4)

In [49]:
oneDim = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])

In [51]:
oneDim.shape

(12,)

In [64]:
twoDim = np.array([[10, 20, 11, 13],[10, 20, 11, 13],[10, 20, 11, 13]])
twoDim.shape

(3, 4)

In [68]:
threeDim = np.array(
    [
        [[1,3,4,5],[1,3,4,5],[1,3,4,5],[1,3,4,5],[1,3,4,5]],
        [[1,3,4,5],[1,3,4,5],[1,3,4,5],[1,3,4,5],[1,3,4,5]]
    ]
)
threeDim.shape

(2, 5, 4)

In [71]:
np.zeros((12,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
arr1

array([10, 20, 30])

In [79]:
arr1[1]

20

In [80]:
arr3

array([[10, 20, 30],
       [21, 32, 11]])

In [83]:
arr3[1][2]

11

In [85]:
arr3[1, 2]

11

In [86]:
arr3[0]

array([10, 20, 30])

In [87]:
arr3[:,1]

array([20, 32])

In [89]:
arr3dim.mean()

5.0

In [90]:
arr3.std()

8.399735445569435

In [92]:
arr3.mean(0)

array([15.5, 26. , 20.5])

In [95]:
arr3.var()


70.55555555555556

In [97]:
arr3.min()


10

In [98]:
arr3.max()

32

In [101]:
for x in arr3:
    print(x)

[10 20 30]
[21 32 11]


In [102]:
for x in np.nditer(arr3):
    print(x)

10
20
30
21
32
11


In [125]:
np.save("new array", arr3)

In [126]:
np.savetxt("new_array.txt", arr3, delimiter='\t')

In [128]:
np.loadtxt("new_array.txt", delimiter='\t')

array([[10., 20., 30.],
       [21., 32., 11.]])